# Herdr user configuration.
# Full reference: https://herdr.dev/docs/configuration

[keys]
prefix = "ctrl+a"

[theme]
name = "vesper"

auto_switch = false
[theme.custom]
panel_bg = "transparent"
sidebar_bg = "transparent"
surface0 = "transparent"
surface1 = "transparent"

[ui.toast]
delivery = "terminal"

